<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use Faker\Generator as Faker;
use App\Dish;

$factory->define(Dish::class, function (Faker $faker) {

  $dishes = [
    [
      'nome'=> 'carbonara',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'pizza',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'amatriciana',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'gricia',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'puttanesca',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'margherita',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '8.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'cannelloni',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'lasagne',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'aranciata',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'birra',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'cocacola',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'filetto',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'pesto',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'rognone',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'zucca',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '5.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'carbonara',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'pizza',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'amatriciana',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'gricia',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'puttanesca',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'margherita',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '8.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'cannelloni',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'lasagne',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'aranciata',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'birra',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'cocacola',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'filetto',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'pesto',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'rognone',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'zucca',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '6.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'carbonara',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'pizza',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'amatriciana',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'gricia',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'puttanesca',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'margherita',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '8.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'cannelloni',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'lasagne',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'aranciata',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'birra',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'cocacola',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'filetto',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'pesto',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'rognone',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ],
    [
      'nome'=> 'zucca',
      'ingredienti'=> 'pancetta',
      'descrizione'=> 'buona',
      'prezzo'=> '7.00',
      'visibilita'=> true,
    ]
  ];

  $index = $faker -> unique() -> numberBetween(0, 44);
  $dish = $dishes[$index];

  return [

    'nome' => $dish['nome'],
    'ingredienti' => $dish['ingredienti'],
    'descrizione' => $dish['descrizione'],
    'prezzo' => $dish['prezzo'],
    'visibilita' => $dish['visibilita'],
  ];
});
